### ISSUE TITLE
No such file or directory: 'requirements.txt\r'

### ISSUE THREAD

**Issue by 5no0p** [mm-io/hasura-django-starter#20]
For reason he didn't find  requirements.txt
```
: not found   | entrypoint.sh: 2: 
hds-django    | Ensuring dependancies are up-to-date...
hds-django    | ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt\r'
hds-django    | 
hds-django    | [notice] A new release of pip available: 22.3.1 -> 23.0.1
hds-django    | [notice] To update, run: pip install --upgrade pip
hds-django    | Making migrations...
hds-django    | Traceback (most recent call last):
hds-django    |   File "/django/manage.py", line 10, in main
hds-django    |     from django.core.management import execute_from_command_line
hds-django    | ModuleNotFoundError: No module named 'django'
hds-django    |
hds-django    | The above exception was the direct cause of the following exception:
hds-django    |
hds-django    | Traceback (most recent call last):
hds-django    |   File "/django/manage.py", line 21, in <module>
hds-django    |     main()
hds-django    |   File "/django/manage.py", line 12, in main
hds-django    |     raise ImportError(
hds-django    | ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

**Comment by 5no0p** [comment]
This issue is related to Windows ... I found the solution in this answer [[...]](https://stackoverflow.com/a/32973565/15303006).
Open entrypoint.sh with [Notepad++](https://notepad-plus-plus.org/)
Edit -> EOL conversion -> Unix/OSX format
And save your file.
